name: tart
description: twirp library for dart
version: 0.1.0
# homepage: https://www.syncapod.com/tart

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
